version: '3'

services:
  nodejs_app_{ENV}:
    image: cantran/labs-devops:{tag}
    build:
      context: nodejs-app/.
      dockerfile: Dockerfile
    container_name: nodejs_app_{ENV}
    # depends_on:
    #   - db
    ports:
      - "{API_PORT}:3000"
    environment:
      DB_HOST: db
      # DB_USER: training
      # DB_PASSWORD: training_pw
      # DB_DATABASE: users
    networks:
      - apps-network-{ENV}

networks:
  apps-network-{ENV}:
    # external: true
