version: '3'

services:
  nodejs_app:
    image: [dockerhub-repo]:{tag}
    build:
      context: nodejs-app/.
      dockerfile: Dockerfile
    container_name: nodejs_app
    # depends_on:
    #   - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      # DB_USER: training
      # DB_PASSWORD: training_pw
      # DB_DATABASE: users
    networks:
      - apps-network

networks:
  apps-network:
    external: true
