apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: api
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: cantran/labs-devops:{tag}
          ports:
            - name: http
              containerPort: {API_PORT}
          env:
            - name: API_PORT
              value: {API_PORT}
          livenessProbe:
            exec:
              command:
                - "true"
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 15
